version: 2
updates:
  # Composer dependencies for PHP
  - package-ecosystem: "composer"
    directory: "/" # Root directory where composer.json is located
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "php" # Ignore platform dependencies (optional)

  # npm dependencies for Sage 10
  - package-ecosystem: "npm"
    directory: "/web/app/themes/sage"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
