version: '3.9'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3030:3306"
    volumes:
      - data:/var/lib/mysql
      - .db/db.sql:/docker-entrypoint-initdb.d/db.sql

  bedrock:
    build:
      context: .
      dockerfile: ./build/bedrock.dockerfile
    container_name: bedrock
    restart: always
    links:
      - mariadb
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - ./:/srv/bedrock

volumes:
  data:
